### ISSUE TITLE
HLS iOs hack working intermitently in Safari

### ISSUE THREAD

**Issue by yarandoo** [MetaCDN/videojs-vr#10]
Thanks for the iOS hack #8. I could verify it is working though not all the times.

When using the video-js-vr plugin with our player(Brightcove). I am facing some issues where the isHLS() function, which is part of the logic to apply the IOS hack, is not correctly working. In desktop and mobile Safari.

I have identified the issue to be that some times at the moment of executing isHLS() - videoEl.src comes empty. Then the logic to match with the list of sources fails. 

Any ideas why the videoEl.src can be empty on some ocassions? One out of ten times the src will be correctly populated and the hack applied correctly.

Can the isHLS logic be simplified to use player.currentType()?

Thanks!

```
<video data-account="92****001"
data-player="r**JIAhuaDg"
data-embed="default"
data-application-id
class="video-js"
controls
crossOrigin="anonymous"
playsinline
preload="auto"
webkit-playsinline
style="width: 100%; height: 100%; position: absolute; top: 0px; bottom: 0px; right: 0px; left: 0px;">
  <source src="https://secure.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=530***001&secure=true" type="application/x-mpegURL">
</video>
```

**Comment by jbroberg** [comment]
Thanks for the report - can you shoot me through a hosted example of your issue (either here or privately)?

**Comment by yarandoo** [comment]
Sent.

**Comment by jbroberg** [comment]
I just pushed a new release with your suggestion @yarandoo  - can you let me know if it fixes your issue?

**Comment by jbroberg** [comment]
Closing - feel free to comment if you still have issues.
