### ISSUE TITLE
Player with fixed size

### ISSUE THREAD

**Issue by yarandoo** [MetaCDN/videojs-vr#11]
Hi, 

When I tried using the plugin in a player with a width and height different than 100% (Ie: 600px X 500px) the Webvr-buttons are not placed correctly(Outside the player) and the fullscreen toggle does not work correctly neither. 

Is this plugin intended to only be used with a video occupying 100% of the screen?. Should I be using the i-frame approach if I want a non fullscreen sized player?

Thanks!

Esteban

**Comment by jbroberg** [comment]
Hi @yarandoo - definitely recommend the iframe approach for sizing the player. That's how we use it internally anyway.
