### ISSUE TITLE
Remote assets for testing in `local-samples` script not loading

### ISSUE THREAD

**Issue by kfarr** [MetaCDN/videojs-vr#14]
The `npm run local-samples` no longer works and returns `Couldn't connect to https://videojs-vr.s3.amazonaws.com/0.2.2/samples/milford-sound.webm (404)`

That said, I was able to download files from the hosted example by manually downloading them.

I'd suggest we revise the `local-samples` script to mirror the exact same samples used in the hosted example.

**Comment by jbroberg** [comment]
Hi @kfarr - added the missing asset.

**Comment by kfarr** [comment]
thanks fixed!
