### ISSUE TITLE
Can't play on Iphone - latest version

### ISSUE THREAD

**Issue by deanngo791** [MetaCDN/videojs-vr#20]
* https://videojs-vr.s3.amazonaws.com/latest/example.html
Above link can't play on Iphone both safari and chrome: 
- Iphone 5s
- Iphone 6
- Iphone 6s +
- No error in console: http://prntscr.com/euj2m5
- Video player loading forever: http://prntscr.com/euj3du
* on desktop, Player work like a boss.
* https://videojs-vr.s3.amazonaws.com/0.3.0/example.html - This version also work like a champ.
How can I make player working on iphone with latest version ?

Thanks !

**Comment by jbroberg** [comment]
Hi there

As per the readme:

> To test macOS and iOS devices with Safari, you need a local/same domain source file. After running npm run local-samples, visit localhost:3000/example-local.html an MP4 sample Hosted example OR visit localhost:3000/example-local-hls.html for a HLS sample Hosted example

Try these
https://videojs-vr.s3.amazonaws.com/latest/example-local.html
https://videojs-vr.s3.amazonaws.com/latest/example-local-hls.html

cheers

James

**Comment by deanngo791** [comment]
@jbroberg Thanks for this reply !
Strange,
https://videojs-vr.s3.amazonaws.com/latest/example-local.html
https://videojs-vr.s3.amazonaws.com/latest/example-local-hls.html
2 above link doesn't work on my Iphone. 
![image](https://cloud.githubusercontent.com/assets/16254144/24850758/78d22434-1dfb-11e7-8bd1-04a3067e32ec.png)

How can I get the 0.3.0 version ?

**Comment by jbroberg** [comment]
Hey @deanngo791 - is that Chrome?

Can you try Safari? Make sure you load in in Safari standalone (e.g. not by following a link from another app).

The hosted example is a couple versions old - I will update that shortly.

cheers - James
