### ISSUE TITLE
How can we integrate videojs-vr in aframe : aframe.io/

### ISSUE THREAD

**Issue by codechikbhoka** [MetaCDN/videojs-vr#21]
I want to have video-js vr as a 360 degree video player instead of aframe's own a-videosphere because video-js vr has support for HLS stream and a-videosphere doesn't. How can I do it ?

**Comment by jbroberg** [comment]
Hey @kfarr did you have some thoughts on this? @codechikbhoka I think the question more broadly is how do you integrate VideoJS itself into a-frame.

Alternatively (if that approach is too heavy weight) you could consider integrating a library like hls.js directly into a-videosphere.

**Comment by codechikbhoka** [comment]
Is everybody connected here :P. I have put up this question here after discussing with @kfarr

**Comment by jbroberg** [comment]
Haha - kinda in this 360/VR space! If the objective is to just get HLS support on desktop with a-frame videosphere you should I'd say the fastest way is the HLS.js route.

**Comment by codechikbhoka** [comment]
you mentioned "desktop" specifically for the HLS.js approach. Do you think it requires more efforts for mobile (android) or HMD's like oculus. Webvr part is handled by a-frame itself, then what more problem is there ?

**Comment by jbroberg** [comment]
I'd say (in theory) it's actually easier on mobile. Desktop browsers like Chrome/Firefox don't have native HLS support so need a 3rd party library to do so.

Chrome on Android has a HLS engine which means no 3rd party libraries should be needed. You should just be able to set your video source to be a HLS m3u8. I've never tried it with  a-videosphere however.

**Comment by codechikbhoka** [comment]
Thanks @jbroberg  and @kfarr, my problem is solved now. hls.js works with a-videosphere straight away
