### ISSUE TITLE
update npm build

### ISSUE THREAD

**Issue by kfarr** [MetaCDN/videojs-vr#22]
Hi @jbroberg, via email @mitch-tofi mentioned to me:

> I tried updating the solution to use npm for videojs-vr, however the most recent package doesn't include our changes (removing the player), even though the branch has been merged in.

Can you bump the npm package?

**Comment by jbroberg** [comment]
npm package updated to 0.3.4 - should include the latest changes.

**Comment by jbroberg** [comment]
@mitch-tofi @kfarr All good now?

**Comment by mitch-tofi** [comment]
@jbroberg yep worked a treat! thanks :)
