### ISSUE TITLE
Decide on 360 format variable name and allowable values.

### ISSUE THREAD

**Issue by jbroberg** [MetaCDN/videojs-vr#4]
Options / prior art:
* Samsung Internet for Gear VR
http://developer.samsung.com/technical-doc/view.do?v=T000000270
* Samsung VR (formerly MilkVR)
https://samsungvr.com/portal/content/faq_tech_gear_vr
* Oculus Video
https://support.oculus.com/help/oculus/913156505462211/

**Comment by jbroberg** [comment]
Samsung Internet:
> dimension=3d-lr: Side-by-Side 3D Video
> dimension=3d-tb: Top-to-bottom 3D Video
> dimension=360: 360˚ Video
> dimension=360-lr: Side-by-side 3D 360˚ Video
> dimension=360-tb: Top-to-bottom 3D 360˚ Video
> dimension=180: 180˚ Video
> dimension=180-lr: Side-by-side 3D 180˚ Video
> dimension=180-tb: Top-to-bottom 3D 180˚ Video

Samsung VR:
Pretty impenetrable, gonna ignore them. 

Oculus Video
> “_TB.mp4” or "_360_TB.mp4" - Top / bottom 3D
> “_BT.mp4” or "_360_BT.mp4" - Bottom / top 3D
> “_LR.mp4” or "_360_LR.mp4" - Left / right side by side 3D
> “_RL.mp4” or "_360_RL.mp4" - Right / left side by side 3D

**Comment by jbroberg** [comment]
Current plugin naming scheme:
projections = ["360", "360_LR", "360_TB", "360_CUBE", "NONE"]

So pretty consistent with both Samsung Internet for Gear VR and Oculus Video.

**Comment by jbroberg** [comment]
@kfarr - Did you get any feedback on projection / format standard at w3c workshop? 

Otherwise will just stick with what I have.

**Comment by kfarr** [comment]
What you have is great. No standard defined yet.

**Comment by jbroberg** [comment]
Sticking with what we have.
