### ISSUE TITLE
Cardboard

### ISSUE THREAD

**Issue by heff** [MetaCDN/videojs-vr#7]
This is great! I have a lowly cardboard. Any blockers to getting it to work there?

**Comment by kfarr** [comment]
No it should "just work": https://github.com/MetaCDN/videojs-vr/wiki/Browser-Compatibility

Except in cases when we use a browser from our friends in Cupertino...

**Comment by kfarr** [comment]
@jbroberg made a separate hosted demo for testing iOS: https://videojs-vr.s3.amazonaws.com/0.2.2/example-local.html

Note all objects must be on the same domain as iOS doesn't properly respect CORS when using webgl

**Comment by jbroberg** [comment]
Hey @heff as @kfarr said it should just work. If you are using iOS device try the 'local' hosted demo. Otherwise if it's still not working let me know the phone, os and browser you are using.

**Comment by heff** [comment]
If I'm going to test cardboard do I need a source that's already split screen, or can this plugin handle splitting the screen somehow?

**Comment by kfarr** [comment]
It'll do it for you! Fancy!

**Comment by jbroberg** [comment]
On your phone, hit the google cardboard icon on the top right of screen (appreciate it's a little small on mobile).

https://videojs-vr.s3.amazonaws.com/0.2.2/example-local.html

**Comment by kfarr** [comment]
As an aside, in the future it may make sense to integrate the cardboard/vr icon with the menu bar...

**Comment by jbroberg** [comment]
@kfarr agreed, we touched on this on slack. there is duplication of the fullscreen icon right now in the current setup also.

**Comment by heff** [comment]
So cool! Silly me for just trying it on my desktop and making assumptions.
This is a powerful plugin.
