### ISSUE TITLE
Odd display on vr headset htc vive with chromium 12-23 build

### ISSUE THREAD

**Issue by kfarr** [MetaCDN/videojs-vr#9]
![screenshot 2](https://cloud.githubusercontent.com/assets/470477/22161296/b39d34a0-df17-11e6-92ea-ee88799f1211.png)

Platform / Device: Windows 10 / Chromium 2016-12-23 build / HTC Vive
Reproducible Code Snippet or URL: use the local-example on htc vive and point to the webm version of the sample video assets (note I had to pull this from the metacdn CDN instead of the videojsvr s3 bucket)

**Comment by jbroberg** [comment]
Thanks for the issue report 

That was odd about it? out of alignment (e.g. the stereo effect was out of wack).

Did you have this same issue with the previous version?

I will try and reproduce myself.

**Comment by jbroberg** [comment]
@kfarr I cannot reproduce this under W10 / Chromium 2016-12-23 build / HTC Vive. It works for me as expected. 

I don't have the headset mirror screen that you have in your screenshot on my desktop - is that some kinda of debug mode?

**Comment by jbroberg** [comment]
Sorry - I should note that I tested with https://videojs-vr.s3.amazonaws.com/0.3.0/example.html which also has the webm. I don't think what you did should be any different though.

**Comment by kfarr** [comment]
can't reproduce on my home computer with vive, closing this
